// Team logo URLs, sourced from SportsDataIO's AllTeams endpoint (WikipediaLogoUrl
// field) — publicly hosted on Wikipedia Commons, no auth required. Matches the
// team_code values actually used in the players table.
export const TEAM_LOGOS: Record<string, string> = {
  ARI: 'https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg',
  ATL: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg',
  BAL: 'https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg',
  BUF: 'https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg',
  CAR: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg',
  CHI: 'https://upload.wikimedia.org/wikipedia/en/1/15/Chicago_Bears_logo_primary.svg',
  CIN: 'https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg',
  CLE: 'https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg',
  DAL: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg',
  DEN: 'https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg',
  DET: 'https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg',
  GB:  'https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg',
  HOU: 'https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg',
  IND: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg',
  JAX: 'https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg',
  KC:  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Kansas_City_Chiefs_logo.svg/120px-Kansas_City_Chiefs_logo.svg.png',
  LAC: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Los_Angeles_Chargers_logo.svg',
  LAR: 'https://upload.wikimedia.org/wikipedia/en/1/14/LA_Rams_logo.svg',
  LV:  'https://upload.wikimedia.org/wikipedia/en/4/48/Las_Vegas_Raiders_logo.svg',
  MIA: 'https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg',
  MIN: 'https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg',
  NE:  'https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg',
  NO:  'https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg',
  NYG: 'https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg',
  NYJ: 'https://upload.wikimedia.org/wikipedia/commons/6/69/New_York_Jets_2024.svg',
  PHI: 'https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg',
  PIT: 'https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg',
  SEA: 'https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg',
  SF:  'https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg',
  TB:  'https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg',
  TEN: 'https://upload.wikimedia.org/wikipedia/en/5/53/Tennessee_Titans_Logo_2026.svg',
  WAS: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Washington_Commanders_logo.svg',
};
